import { Metadata } from 'next'; // This line is unnecessary unless you need the Metadata type
export const getPageTitle = async (path) => {
    const titles = {
      '/': 'United Technologies of Success',
      '/about': 'About Us',
      '/services': 'Our Services',
      '/design': 'Design',

      '/ru': 'Главная',
      '/ru/services': 'Услуги и цены', 
      '/ru/design': 'Дизайн сайта',
      '/ru/landing': 'Разработка лендинга',
      '/ru/web-development': 'Создание сайта',
      '/ru/web-development/wordpress': 'Создание сайтов на Wordpress',
      '/ru/web-development/opencart': 'Создание сайтов на OpenCart',
      '/ru/web-development/laravel': 'Создание сайтов на Laravel',
      '/ru/web-development/react-next-js': 'Создание сайтов на React / Next.js',
      '/ru/web-development/saas': 'Создание сайтов на конструкторе',
      '/ru/online-store-development': 'Разработка интернет-магазина',
      '/ru/web-development/marketplace': 'Создание маркетплейса',
      '/ru/web-development/auction': 'Создание аукциона',
      '/ru/web-development/portal': 'Разработка онлайн-портала',
      '/ru/seo': 'SEO продвижение сайта',
      '/ru/seo-online-store': 'Раскрутка интернет-магазина',
      '/ru/seo-on-development': 'SEO на этапе разработки',
      '/ru/ads': 'Онлайн реклама',
      '/ru/blog': 'Блог',
      '/ru/blog/what-is-pbn': 'Что такое PBN и как они используются?',
      '/ru/blog/what-is-alexa': 'Что такое рейтинг Alexa и правильное его использование в SEO',
      '/ru/blog/research-sample-b2b': 'Проведение B2B маркетинговых исследований: особенности, трудности и выборка',
      '/ru/blog/pr-b2b': 'PR в B2B сегменте. Продвижение B2B-компаний',
      '/ru/blog/research-sample-b2c': 'Определение размера выборки в маркетинговых исследованиях (B2C)',
      '/ru/blog/behance': 'Раскрутка аккаунта в Behance — продвижение услуг дизайнера',
      '/ru/blog/product-levels': 'Уровни товара в фундаментальном маркетинге',
      '/ru/blog/baidu-seo': 'Продвижение сайта в Baidu (Байду): домен, хостинг, SEO в Китае',
      '/ru/blog/baidu-sign-up': 'родвижение в Китае. Регистрация сайта в Baidu (Байду, 百度)',
      '/ru/blog/chinese-digital-marketing': 'Интернет маркетинг в Китае',
      '/ru/online-services': 'Онлайн сервисы',
      '/ru/seo-cost-calculator': 'SEO онлайн калькулятор',
      '/ru/web-development-cost-calculator': 'Оценка стоимости веб-разработки онлайн',
      '/ru/privacy': 'Политика конфиденциальности',
      '/ru/cookies': 'Политика Cookies',
      '/ru/legal': 'Юридическая информация',
      '/ru/sitemap': 'Карта сайта',
      '/ru/reviews': 'Отзывы о компании',
      '/ru/company': 'О компании',
      '/ru/contact': 'Контакты',
      '/ru/cases': 'Наши работы',
      '/ru/cases/zplay': 'Создание сайта ведущего китайского разработчика игр ZPLAY',
      '/ru/cases/okko': 'Дизайн, техподдержка и разработка разделов на сайте сети ОККО',
      '/ru/cases/roganska': 'Дизайн и разработка сайта для бренда Роганская вода',
      '/ru/cases/carglass': 'Разработка сайта Carglass',
      '/ru/cases/health-ua': 'Разработка портала Health-UA',
      '/ru/cases/hyundai': 'Разработка сайта автодилера Hyundai',
      '/ru/cases/varvar': 'Дизайн интернет-магазина VARVAR',
      '/ru/cases/lamps4makeup': 'Дизайн и разработка интернет-магазина Lamps4makeup',
      '/ru/cases/agro': 'Разработка сайта для агрокомпании',
        '/ru/cases/molekula': 'Дизайн и создание медицинского сайта для МЦ Молекула',
        '/ru/cases/rannov': 'Создание интернет-магазина одежды RANNOV',
        '/ru/cases/jinsovik': 'Дизайн интернет-магазина одежды Джинсовик',
        '/ru/cases/yumi': 'Дизайн сайта для китайского сервиса монетизации Yumi',
        '/ru/cases/modiva': 'Разработка интернет-магазина Modiva',
        '/ru/cases/palvira': 'Разработка и продвижение интернет-магазина Palvira',
        '/ru/cases/avers': 'Продвижение сайта агентства недвижимости',
        '/ru/cases/masshold': 'Рекламная кампания для интернет магазина Masshold',
        '/ru/cases/prom-ua': 'Создание и продвижение интернет-магазина на Prom.ua',
        '/ru/cases/building': 'Разработка сайта застройщика Витязь СтройЦентр',
        '/ru/cases/toyota': 'Редизайн сайта автосалона официального дилера Toyota',
        '/ru/cases/meblix': 'Разработка мебельного интернет-магазина Мебликс',
        '/ru/cases/bus365': 'Создание сайта транспортной компании',
        '/ru/cases/meridian': 'Создание нишевого маркетплейс MeridianNurse',
        '/ru/cases/32': 'Дизайн сайта для компании 32.in.ua',
        '/ru/cases/startup': 'Дизайн и разработка сайта для IT стартапа',
        '/ru/cases/a1': 'Разработка сайта для студии архитектурной визуализации',
        '/ru/cases/megazayka': 'Редизайн сайта магазина детских товаров MegaZayka',
        '/ru/cases/aesthetta': 'Создание сайта клиники эстетической косметологии Aesthetta (США)',
        '/ru/cases/spetslaw': 'Разработка и продвижение юридической компании из США',
        '/ru/cases/ultracash': 'Продвижение сервиса онлайн кредитов Ultracash',
        '/ru/cases/dental': 'Продвижение клиники Стоматология для всех',
        '/ru/cases/dverman': 'Продвижение и редизайн сайта Dverman',
        '/ru/cases/toptv': 'Создание и продвижение интернет-магазина электроники и бытовой техники',
        '/ru/cases/rmc': 'Разработка и продвижение медицинского центра',
        '/ru/cases/luxel': 'Разработка и продвижение интернет магазина электротехники',
        '/ru/cases/pesochinsky': 'Разработка и продвижение проекта новостройки',
        '/ru/cases/sinbad': 'Продвижение сайта транспортной компании',
        '/ru/cases/skydrive': 'Продвижение службы такси',
        '/ru/cases/chmsoft': 'Разработка сайта IT компании Chmsoft',
        '/ru/cases/utopia': 'SEO и техподдержка фреймворка Utopia',
        '/ru/cases/hited': 'Разработка интернет-магазина Hited',
        '/ru/cases/steli': 'Дизайн маркетплейса Steli.top',
        '/ru/cases/legalgrounds': 'Создание сайта LegalGround.top',
        '/ru/cases/konterowanie': 'Разработка и дизайн аукциона (Польша)',
        '/ru/cases/spaceunder': 'Разработка и дизайн интернет-магазина Spaceunder',
        '/ru/cases/showme': 'Разработка лендинга ShowMe для продвижения в Китае',
        '/ru/cases/revitalbeauty': 'Разработка и дизайн лендинга для немецкой клиники RevitalBeauty',
        '/ru/cases/ukreina': 'Разработка и дизайн интернет-магазина Ukreina',
        '/ru/cases/procraft': 'Разработка интернет-магазина Procraft'
    };
  
    return titles[path] || null;
  };