"use client";

import React, { useEffect, useState } from 'react';
import axios from 'axios';

const IpInfo = () => {
  const [ipData, setIpData] = useState<{ ip: string; country: string } | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        // Используем API ipinfo.io для получения данных о пользователе
        // 476f3ed8dbaf96
        const response = await axios.get('https://ipinfo.io/json?token=476f3ed8dbaf96');
        const { ip, country } = response.data;
        setIpData({ ip, country });
      } catch (error) {
        console.error('Ошибка при получении данных:', error);
      }
    };

    fetchData();
  }, []);

  return (
    <div style={{ textAlign: 'center', marginTop: '20px' }}>
    {/* Имитация полей входа в админку */}
    <div style={{ marginBottom: '20px' }}>
      <div
        style={{
          width: '300px',
          height: '40px',
          backgroundColor: '#f0f0f0',
          margin: '0 auto 10px auto',
          borderRadius: '4px',
          opacity: '0.5',
        }}
      ></div>
      <div
        style={{
          width: '300px',
          height: '40px',
          backgroundColor: '#f0f0f0',
          margin: '0 auto',
          borderRadius: '4px',
          opacity: '0.5',
        }}
      ></div>
    </div>
        
      {ipData ? (
        <>
          <p style={{fontWeight: '700'}}>Your IP: {ipData.ip}</p>
          <p>Location: {ipData.country}</p>
        </>
      ) : (
        <p>Loading...</p>
      )}
      <h3 style={{ fontWeight: '300', marginBottom: '10px', color: 'red' }}>Your IP is not on the list of allowed addresses to access the login page</h3>
      <div style={{ marginTop: '120px', marginBottom: '0px' }}>
        <p style={{fontSize: '13px'}}>Generated by WordPress Limitations Pro (1.82)</p>
        <br/>
        <br/>
        <br/>

      </div>
    </div>
  );
};

export default IpInfo;
