import * as React from 'react';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "3Web Machine Rocks!",
  description: "3Generated by Web Machine Rocks",
};

const About = () => {
  return (
    <div>
      <h1>About Page</h1>
    </div>
  );
};

export default About;

