import type { Metadata } from "next";
import HeadComponent from './head'; 
import { Unbounded } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Major_Mono_Display } from "next/font/google";
import "./globals.css";
import CookieBanner from '../components/cookiesbanner/CookieBanner';
import React from 'react';
import { headers } from 'next/headers';
import Script from 'next/script';


const unbounded = Unbounded({ subsets: ["latin", "cyrillic-ext"] });
const montserrat = Montserrat({ subsets: ["latin", "cyrillic-ext"] });
const majorMonoDisplay = Major_Mono_Display({ subsets: ["latin"], weight: ['400'], variable: '--font-major-mono-display' });

export const metadata: Metadata = {
  title: "Web Machine Rocks!",
  description: "Generated by Web Machine Rocks",
  icons: {
    icon: '/web-machine-rocks-logo-2024.svg'
  },
  robots: "index,follow",
  generator: "Typescript",
  verification: { google: ""},
};

// export default function RootLayout({children,}: {children: React.ReactNode;}) {
//  return (
//<html lang="en" dir="ltr">

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const requestHeaders = headers();

  const lang = requestHeaders.get('x-lang') || 'en';
  return (
    <html lang={lang} dir="ltr">
      <head>
          <meta name="theme-color" content="#1af287" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
          <meta itemScope itemType="https://schema.org/Organization" />
          <meta itemProp="name" content="WEB-MACHINE" />
          <meta itemProp="logo" content="https://web-machine.rocks/images/main/web-machine-logo.png" />
          <meta itemProp="url" content="https://web-machine.rocks/" />
          <meta itemProp="telephone" content="+38 068 112 112 8" />
          <meta itemProp="streetAddress" content="вул. Дорогожицька, 3" />
          <meta itemProp="addressLocality" content="Киев, Украина" />

          <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-X6PCHTYTKR"
          strategy="afterInteractive"
          />
          <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-X6PCHTYTKR');
          `}
          </Script>
        <HeadComponent />
      </head>
      <body className={montserrat.className}>
        {children}
        <CookieBanner />
      </body>
    </html>
  );
}