// app/layout.tsx
import type { Metadata } from "next";
import HeadComponent from './head'; 
import { Unbounded } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";

const unbounded = Unbounded({ subsets: ["latin", "cyrillic-ext"] });
const montserrat = Montserrat({ subsets: ["latin", "cyrillic-ext"] });

export const metadata: Metadata = {
  title: "Web Machine Rocks!",
  description: "Generated by Web Machine Rocks",
};

export const HeadAdd = () => {
return (
  <>
<head>
<script src="https://www.googletagmanager.com/gtag/js?id=G-8Y0XBRKL31&amp;cx=c&amp;_slc=1" async></script>
</head>
</>
)
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <HeadAdd></HeadAdd>
    <HeadComponent />
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
