import Image from "next/image";
import type { Metadata } from "next";
import Link from 'next/link';
import Head from 'next/head';
import LayoutMain from "../components/LayoutMain";
import MainComponent from "@/components/MainComponent";

export const metadata: Metadata = {
  title: "112 Web Machine Rocks!",
  description: "112 Generated by Web Machine Rocks",
  robots: "index,follow",
  alternates: {
    canonical: "https://web-machine.rocks/",
    languages: {
      en: "https://web-machine.rocks/",
      ru: "https://web-machine.rocks/ru/",
      uk: "https://web-machine.rocks/uk/",
    },
  },
};


export default function Home() {
  return (
    <>
<LayoutMain>
    <MainComponent></MainComponent>
</LayoutMain>
    </>
  );
}
