import { ReactNode } from 'react';
import dataArticles from "../../utils/dataArticles";
import "../globals.css";

export async function generateMetadata({ params }: { params: { slug: string } }) {
  const { slug } = params;
  const articlePageTitle = dataArticles.articles.find(item => item.slug === slug);

  return {
    title: articlePageTitle ? articlePageTitle.title : 'Default Title',
    description: 'Generated by Next.js',
  };
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  );
}
