import * as React from 'react';
import Head from 'next/head';
import styles from './RuStyle.module.css'
import type { Metadata } from "next";
import LayoutMainRus from "@/components/LayoutMainRus";
import MainComponentRus from '@/components/MainComponentRus';

export const metadata: Metadata = {
  title: "Руссс!",
  description: "2Generated by Web Machine Rocks",
};

const RusMain = () => {
  return (
 
  <LayoutMainRus>
  <MainComponentRus></MainComponentRus>
</LayoutMainRus>
  );
};

export default RusMain;
