import * as React from 'react';
import Head from 'next/head';
import styles from './RuStyle.module.css'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Руссс!",
  description: "2Generated by Web Machine Rocks",
};

const Test = () => {
  return (
    <>
      <div className={styles.backgroundru}>
        <h1 className={styles.text_white}>Главная русскоязычная</h1>
        <h2 className={styles.text_white}>тест lang</h2>
      </div>
    </>
  );
};

export default Test;
